FROM node:21.7.1

WORKDIR /usr/src/app

COPY package*.json package-lock.json nest-cli.json ./

COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

EXPOSE 3001
EXPOSE 1234

CMD [ "npm", "run", "start:prod" ]